package com.hashtable;
/*
 * 389. Find the Difference
 * Given two strings s and t which consist of only lowercase letters.

	String t is generated by random shuffling string s and then add one more letter at a random position.
	
	Find the letter that was added in t.
 */
public class Main3 {
	public static void main(String[] args) {
		Main3 main3=new Main3();
		String s = "abcd";
		String t = "abcde";
		System.out.println(main3.findTheDifference(s, t));
	}
	public char findTheDifference(String s, String t){
		int[] hansh=new int[26];
		for(int i=0;i<s.length();i++){
			hansh[s.charAt(i)-'a']++;
			
		}
		for(int i=0;i<t.length();i++){
			hansh[t.charAt(i)-'a']--;
			if(hansh[t.charAt(i)-'a']<0){
				return t.charAt(i);
			}
		}
		return '-';
	}
}
